# Site settings
title: New Directions
header-img: img/home-bg3.jpg
email: newdirectionsphilmind@gmail.com
description: "New Directions in the Study of the Mind Project."
baseurl: http://www.newdirectionsproject.com
siteurl: http://www.newdirectionsproject.com
twitter_username: studyofthemind
facebook_username: newdirectionsmindproject
instagram_username: newdirectionsproject
future: true

# Build settings
markdown: kramdown
# highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Construction text
underconstruction: "coming soon"

# Google Analytics
google_analytics: 	UA-63024724-1

# Team names, titles and social links
people:
- name: Tim Crane
  pic: 1
  position: Principal Investigator
  social:
    - title: twitter
      url: https://twitter.com/timcrane102
    - title: linkedin
      url: http://www.linkedin.com/profile/view?id=17801629
    - title: home
      url: http://timcrane.com

- name: Laura Gow
  pic: 6
  position: Postdoctoral Fellow
  social:
    - title: home
      url: http://lauragow.com

- name: Alex Grzankowski
  pic: 3
  position: Lecturer
  social:
    - title: home
      url: http://alexgrzankowski.com/

- name: Raamy Majeed
  pic: 4
  position: Postdoctoral Fellow
  social:
    - title: home
      url: https://raamymajeed.wordpress.com

- name: Alexander Greenberg
  pic: 7
  position: Research Associate and Project Manager
  social:
    - title: home
      url: http://alexandergreenberg.github.io

formerpeople: # Info for new former project team members
- name: Craig French
  pic: 2
  social:
    - title: twitter
      url: https://twitter.com/craigafrench
    - title: home
      url: http://www.craigfrench.co.uk/

- name: Chris Meyns
  pic: 5
  social:
    - title: twitter
      url: https://twitter.com/chrismeyns
    - title: home
      url: http://chrismeyns.xyz

collaborator:
# - name: The Human Mind Project
#   pic:
#   position: School of Advance Study, University of London
#   social:
#     - title: twitter
#       url: https://twitter.com/HumanMindDebate
#     - title: home
#       url: http://humanmind.ac.uk

- name: Centre for Philosophical Psychology
  pic: 9
  position: University of Antwerp
  social:
    - title: home
      url: http://uahost.uantwerpen.be/bence.nanay/

# - name: Leverhulme Centre for the Future of Intelligence
#   pic:
#   position: University of Cambridge
#   social:
#     - title: home
#       url: http://leverhulmecfi.org

# Settings for sharing
    # Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
    # Add a tweet button    => provider : tweet
    # Add a like button     => provider : like (you also need a facebook appid)
    # Add a plus one button   => provider : plusone
    # Add a HN button     => provider : hn
    # Add them all (i.e. hn + tweet + plusone + like) => provider : all
    # Set 'provider' to the sharing provider you want to use.
    # Set 'provider' to false to turn sharing off globally.
    #
     # sharing :
     #   provider : all
     #   twitter :
     #     size :
     #     via :
     #     count :
     # facebook :
     #     appid : 123
     #     layout : button_count
     #     font :
     #     faces : false
     #     width : 90
     # googleplus :
     #     size : medium
     #     width :
     #     annotation : bubble
     # linkedin :
     #     counter : right
